locales/es.yml
Mayor énfasis en lo libre que en lo abierto
=> cambios menores 

locales/en.yml
more emphasis on free and common's than "open"
=> minor changes on content

config.rb, lib/i18n_helpers.rb, locales/ca.yml, locales/en.yml, locales/es.yml, source/layouts/layout.erb, source/localizable/community.ca.html.erb, source/localizable/community.es.html.erb, source/localizable/contract.es.html.erb, source/localizable/credits.ca.html.erb, source/localizable/credits.es.html.erb, source/localizable/credits.html.erb, source/localizable/demo.ca.html.erb, source/partials/navigation.html.erb, source/partials/tracking.html.erb
* Moving piwik to partial
* Changing to same page on click
* Fixing metadata for new pages
* Using full names for languages
=> Several mini fixes for i18n

LICENSE
Maitaining original MIT for first commit
=> Update LICENSE to AfferoGPLv3

config.rb, source/netlify-redirects
Reverts decidim/decidim.org#51
@xabier it wasn't ready for production, see #33
=> Revert "Adding redirects on home for i18n autodetecting browser settings - closes #33"

locales/ca.yml, locales/en.yml, locales/es.yml, source/layouts/layout.erb, source/localizable/index.html.erb, source/partials/alert--expanded.html.erb, source/partials/alert.html.erb, source/stylesheets/modules/_alert.scss, source/stylesheets/site.css.scss
- New alert on top of the page (included in layout.erb) for cross-website announcement of new events and releases.
- New alert section  (alert--expanded, included in index.html.erb) for home page announcements. Can include a description paragraph. 
Please remove/comment these lines when not using them.
Solves #52.
=> Alert blocks for new releases and events

source/stylesheets/modules/_header.scss, source/stylesheets/modules/_lang.scss
Language switcher displayed always on top, with a top bar with a darker color.
Solves #25
=> Top bar with language switcher

locales/ca.yml, locales/en.yml, locales/es.yml, source/javascripts/play-video.js, source/layouts/layout.erb, source/partials/hero.html.erb, source/stylesheets/_variables.scss, source/stylesheets/modules/_play-video.scss, source/stylesheets/site.css.scss
Video in intro section. Solves #61
=> Intro video in home

source/blog/es/2018-04-27-release-0.11.0.html.md
adds new blog entry in Spanish for release 0.11
=> adds new blog entry in Spanish for release 0.11

source/partials/footer.html.erb
So yeah, we're on the fifth month and today someone told me that we should update this...
=> Updates footer with new year

source/layouts/layout.erb, source/partials/navigation.html.erb
=> Removes banner for gov and theme-color for mobile

source/partials/footer.html.erb, source/stylesheets/modules/_footer.scss
=> Netlify badge in footer

source/javascripts/play-video.js, source/partials/video-hero.erb
This improves the loading issues experienced in Firefox.
=> Adds the iframe video with JS to avoid loading issues in Firefox

config.rb, source/blog/index.ca.html.erb, source/blog/index.es.html.erb, source/blog/index.html.erb, source/javascripts/paginate-blog.js, source/layouts/layout.erb, source/stylesheets/modules/_blog.scss
Since there's a reported bug with Middleman blog pagination and i18n, I'm loading all the posts, hiding all but 5 with JS, and then using a "load more" pattern. Fixes #164
=> Moved blog pagination to JS to avoid a Middleman i18n+pagination bug

source/blog/ca/2018-12-13-release-0.15.0.html.md, source/blog/ca/2019-01-14-consul-comparison.html.md, source/blog/ca/2019-01-14-release-0.16.0.html.md, source/blog/ca/2019-03-25-release-0.17.0.html.md, source/blog/es/2018-12-13-release-0.15.0.html.md, source/blog/es/2019-01-14-consul-comparison.html.md, source/blog/es/2019-01-14-release-0.16.0.html.md, source/blog/es/2019-03-25-release-0.17.0.html.md
There were some missing old posts on spanish and catalan languages. This adds them.
=> Adds old blog posts untranslated to es/ca languages

locales/ca.yml, locales/en.yml, locales/es.yml, source/partials/footer.html.erb, source/partials/navigation.html.erb, source/partials/topbar.html.erb
Add modules page on navigation menu. 
We also change the format of "nav*" i18n keys as I prefer using the yaml tree instead of camelCasing it.
=>  Add /modules to navigation menu 

locales/ca.yml, locales/en.yml, locales/es.yml, source/layouts/layout.erb
=> Alert: adds DecidimFest2020 Call

locales/en.yml, source/localizable/legal-notice.html.erb, source/localizable/privacy-policy.html.erb, source/partials/footer.html.erb
Add these two pages. They're linked at the footer:
=> Add legal pages: "Privacy policy" and "Legal notice"

source/blog/en/2021-10-07-new-version-0-25-0.html.md
=> Add a "releases" tag to 0.25 blog post

README.md, data/links.yml, data/press.yml, locales/en.yml, source/localizable/press.html.erb, source/partials/_article_preview.html.erb
* [Fix article summaries on Blog index page](https://github.com/decidim/decidim.org/commit/1d8ba4a638ca5c38f848645b2b9cf2350d1f1c5e)
=>  Fix details on redesign (part 4)

lib/i18n_helpers.rb, source/localizable/first-steps.html.erb
The problem that this was trying to solve (missing translations on other locales) is already handled by i18n-tasks.
=> Drop t_with_default support

config/i18n-tasks.yml, source/admin/config.yml, source/blog/en/2022-09-30-new-version-0-27-0.html.md
Rename "post-en" to "post"
Drop date from configuration and last post
=> Fix Post configuration in Netlify CMS

source/localizable/contact.html.erb, source/localizable/legal-notice.html.erb, source/localizable/partnership-policy.html.erb, source/localizable/privacy-policy.html.erb, source/localizable/trademark-policy.html.erb, spec/system/pages_spec.rb
We have an issue where on some pages the links aren't working correctly. This PR fixes that.
Pages to check: 
- https://decidim.org/trademark-policy/
- https://decidim.org/contact/
- https://decidim.org/legal-notice/
- https://decidim.org/partnership-policy/
=> Fix links on pages with i18n

source/layouts/layout.erb
Someone asked by email lately. 
Fix #112
=> Add HTML tag for RSS discovery

.rubocop.yml, Gemfile, Gemfile.lock, config.rb, data/languages.yml
This PR enables the pt-BR locale. 
🇧🇷 👏🏽
=> Add Portuguese (Brazil) language

.github/workflows/ci_main.yml, .github/workflows/lint_code.yml, locales/en.yml, source/localizable/contact.html.erb, source/stylesheets/components/form-input.css
We have been talking about adding "Reasons for contact" in our contact form. This PR does that.
=> Add reasons on the contact form
